name: my first workflow

on: push

jobs:
    first-job:
        runs-on: ubuntu-latest
        steps:
        - name: checkout repo
          uses: actions/checkout@v4

        - name: my first job 
          run: |
                echo "my first job is awesome" > file.txt
                mkdir myfolder
                mv file.txt myfolder
                cd myfolder
                cat file.txt
                ls -ltra


